print('welcome to yusuf and son')
principal = float(input("enter your initial amount(₦):"))
interest_rate = float(input("enter your initial interest_rate:"))
N = float(input("enter number of time period applied per time:"))
t = float(input("enter number of time period elasped:"))
simple_interest = principal*(1+interest_rate*t)
compound_interest = principal*(1+(interest_rate/N))
print("simple interest =" + str(simple_interest))
print("compound interest =" + str(compound_interest))